= Devoxx France 2019 - Microservices: Spring Cloud vs JEE Microprofile?

Spring Microservices vs MicroProfile JEE

== Darren : 

Voilà la liste des link :

* https://spring.io/guides/gs/rest-service/
* https://spring.io/guides/gs/consuming-rest/
* https://spring.io/guides/gs/spring-boot-docker/
* http://eldermoraes.com/2018/07/31/how-to-implement-microservices-using-microprofile-thorntail-and-eclipse-ide/
* https://developers.redhat.com/blog/2018/11/21/eclipse-microprofile-for-spring-boot-developers/
* https://itnext.io/migrating-a-spring-boot-service-to-kubernetes-in-5-steps-7c1702da81b6
* https://www.e4developer.com/2018/01/21/java-enterprise-and-microservices-meet-microprofile/
* https://medium.com/@the.raj.saxena/springboot-2-performance-servlet-stack-vs-webflux-reactive-stack-528ad5e9dadc
* https://itnext.io/migrating-a-spring-boot-service-to-kubernetes-in-5-steps-7c1702da81b6

== Thomas :

Pour la comparaison de 2 stacks microservices complètes, bien penser à :

* comparer l'outillage associé, dont une base va être commune (ex : SonarQube ?)

Fonctionnalités à comparer :

* API Gateway
* Load Balancer
* Service Discovery
* Circuit Breaker

Des exemples d'outils gérant ces 4 fonctionnalités:

* côté Netflix OSS : Zuul / Ribbon / Eureka / Hystrix
* côté Hashicorp : ??? / Fabio / Consul (très à la mode partout en ce moment) / ???

Netflix est peut-être en train d'abandonner une partie de sa stack, ou de la renouveler Voir par exemple Envoy qui pourrait remplacer Zuul : +
https://piotrminkowski.wordpress.com/2017/10/25/envoy-proxy-with-microservices/

Pour la partie sécurité, dans le EJM, en 206/297, on trouve : +
"Standard protocols— Out of the box, Keycloak provides support for OpenID Connect, OAuth 2.0, and Security Assertion Markup Language (SAML)."

Dans notre plan de prez, on pourrait rappeler les différents composants d'une stack microservices (API gateway, Service discovery, Load Balancer, etc.) +
il faudrait se débrouiller pour faire nos exemples Microprofiles et Spring Boot avec les mêmes outils en commun (quand possible biensûr) +
il faudrait essayer de garder une trame commune, pour faciliter la comparaison

-> On pourrait toucher 2 mots des 12 factor app ? Voir l1 p55

== Plan de la présentation

* Refaire un rien d'histoire *très rapide* sur les microservices (définition d'A. Cockburn, applications cloud native, qualité de service et fonctionnalités attendues, etc.)

* Rappel de l'env tech des microservices, et de la qualité de services attendue concernant ces derniers, pour la réalisation d'une application cloud native :

** API Gateway
** Service Discovery
** Load Balancer
** Design for failure
	**** Circuit Breaker
	**** bulkheads
	**** fallbacks
** Centralised configuration
** monitoring and logging
** security

* Description de la stack Spring Boot et Cloud, et des outils avec lesquels elle s'intègre pour rendre la qualité de service :
	** Netflix OSS
		**** Hystrix
		**** Ribbon -> Eureka
	** Spring actuators (logging monitoring)
	** Spring security

== Préparation des slides

IMPORTANT : faire les slides en FRANCAIS ! (Devoxx FR est à 80% francophone)

Rappelez que les applications sont de plus en plus *cloud native* à l'heure actuelle

The common work of a developper is to:

* develop
* secure (check if we add this step or not?)
* test
* package
* deploy
* monitor
* scale their application

As this can be complex, they generally do rely on frameworks to ease those steps. 

When working with Java, *JEE* and *Spring* and 2 common ones

Pour la partie *MicroProfile* :
Taken as is, JEE is a specification for an Application Server dedicated to monolithic webapps, whereas Spring Boot and Cloud are designed to build microservices. +
One could say there is nothing to compare, "just choose Spring", but that's just when Microprofile comes into play.

So let's compare Spring Boot and Cloud and Microprofile, and to do so let's quickly remind ourselves what are microservices.

Microservices originated from the Hexagonal Architecture, also known as Ports and Adapters pattern, coined by Alistair Cockburn. +
He describes microservices as:

____
an architectural style or an approach to building IT systems as aset of business capabilities that are autonomous, self-contained, and loosely coupled.
____

-> Pour un excellent article sur l'*architecture hexagonale*, voir le blog d'Octo : https://blog.octo.com/architecture-hexagonale-trois-principes-et-un-exemple-dimplementation/ :

----
Allow an application to equally be driven by users, programs, automated test or batch scripts, and to be developed and tested in isolation from its eventual run-time devices and databases.
OU, en français :
Permettre à une application d’être pilotée aussi bien par des utilisateurs que par des programmes, des tests automatisés ou des scripts batchs, et d’être développée et testée en isolation de ses éventuels systèmes d’exécution et bases de données.
----

Pour une présentation *très simple et claire* (vraiment très très bien !), voir également cet article de Xebia : https://blog.xebia.fr/2016/03/16/perennisez-votre-metier-avec-larchitecture-hexagonale/

This implies that they need to be:

* *small*:

.https://dzone.com/articles/microservices-in-practice-1
----
The foundation of microservices architecture(MSA) is about developing a single application as a suite of *small* and *independent* services that are running in its own process, developed and deployed independently.
----

-> on peut également rappeler le "Single Responsibility Principle" de SOLID qui est un point essentiel permettant de définir la taille d'un microservice

* *isolated*
* *reusable*

.https://dzone.com/articles/microservices-in-practice-1
----
In the context of SOA, SOA governance guides the development of reusable services, establishing how services will be designed and developed and how those services will change over time.
----

-> les microservices peuvent être vues comme une *évolution des architectures SOA* : voir https://dzone.com/articles/microservices-in-practice-1

Les "problèmes" de SOA :

.https://dzone.com/articles/microservices-in-practice-1
----
Hence, with SOA, a software application is designed as a combination of 'coarse-grained' services. However, in SOA, THE SCOPE OF A SERVICE IS VERY BROAD. That leads to complex and mammoth services with several dozens of operations (functionalities) along with complex message formats and standards (e.g: all WS* standards).

[...]

In most cases, services in SOA are independent from each other, yet they are deployed *IN THE SAME RUNTIME* along with all other services (just think about having several web applications which are deployed into the same Tomcat instance)
----

"La SOA et les microservices se distinguent principalement sur deux points : *les ESB lourds* et complexes de la SOA sont remplacés par des bus de messages simples sans complexité métier et robustes techniquement" (https://www.journaldunet.com/solutions/cloud-computing/1166432-microservices-est-ce-realiste/1167035-le-concept-des-microservices)

* *disposable*

The need of *failing fast* 

To guarantee those last, a classic technical stack emerged around the following component:

* API Gateway
* Service Discovery
* Load Balancer
* Circuit Breaker
	** bulkheads
	** fallbacks
* Centralised configuration (?)
* monitoring and logging
* security

== Demo et applications

* Spring

* MicroProfile

On prendrait quelle implémentation pour nos tests ?

* OpenLiberty (IBM) est la plus à jour quant à la version d'Eclipse MicroProfile
* Thorntail (ex Wildfly Swarm, RedHat) est "Thorntail, in its 2.1.0.Final version, is the first MicroProfile container to use the SmallRye implementation." +
Voir https://developers.redhat.com/blog/2018/08/23/eclipse-microprofile-and-red-hat-update-thorntail-and-smallrye/

== Resources

* Microservices "core" :
	** https://fr.slideshare.net/BenWilcock1/microservices-java-ee-vs-spring-boot-and-spring-cloud : old (2016), surtout un plébiscite de Spring Boot comparé à JEE
		**** the associated GitHub repo is also very good (https://github.com/benwilcock/cqrs-microservice-sampler) +
		A detailed explanation of the work done is also available at https://benwilcock.wordpress.com/2016/06/20/microservices-with-spring-boot-axon-cqrses-and-docker/
	** https://dzone.com/articles/microservices-in-practice-1: VERY GOOD def of all elements of the microservices stack
	** *Pragmatic Microservices*: https://medium.com/microservices-in-practice/microservices-in-practice-7a3e85b6624c TRES TRES BON +
	Une autre bonne présentation des différents éléments de la stack microservices
	** Toutes les explications du site Eclipse.org sur les bases des microservices et fonctions associées (gateway, service discovery) sont très bien faites. Exemple : https://www.eclipse.org/community/eclipse_newsletter/2017/september/article5.php
	** *applications cloud-native* un bon schéma et une def courte et claire "L'approche Cloud-native est la façon dont les applications sont créées et déployées, non pas où elles sont exécutées." : https://www.supinfo.com/articles/single/5015-qu-est-ce-qu-une-application-cloud-native +
	J'aime également cette définition succincte des applications cloud native : *RESTful APIs that communicate over HTTP with JSON serialization* (https://www.slideshare.net/fortyfivan/microservices-webinar, slide 6)

* Spring Boot and Cloud microservices :
	** Quick Guide to Microservices With Spring Boot 2.0, Eureka, and Spring Cloud : https://dzone.com/articles/quick-guide-to-microservices-with-spring-boot-20-e
	** définition de Spring Boot & Cloud l1 p6

* Eclipse MicroProfile :
	** cette suite d'articles d'Eclipse.org, traitent également de l'env tech autour des microservices : https://www.eclipse.org/community/eclipse_newsletter/2017/september/
	** Red Hat's implementation of Eclipse MicroProfile, WildFly Swarm, has been renamed to *Thorntail*.
	** Eclipse MicroProfile Releases and associated implementation: https://wiki.eclipse.org/MicroProfile/Implementation
	** Here comes *SmallRye*, a shared Eclipse MicroProfile implementation: https://developers.redhat.com/blog/2018/08/23/eclipse-microprofile-and-red-hat-update-thorntail-and-smallrye/
	** dev "core" de microservices avec MicroProfile (sans l'env tech adjacent) : https://www.baeldung.com/eclipse-microprofile

	** env tech avec MicroProfile, voir *KumuluzEE* (Java Duke’s Choice Award Winner) which provides support for service discovery by introducing simple annotations for REST services: https://ee.kumuluz.com/microprofile +
	-> problème : KumuluzEE is fully compliant with Eclipse MicroProfile 1.0, 1.1 and 1.2. -> donc pas les versions les plus récentes
	** Toujours sur KumuluzEE, que l'on pourrait voir comme un concurrent de Spring Cloud : https://piotrminkowski.wordpress.com/tag/microprofile/
	+
	----
	*What’s KumuluzEE*
	Can KumuluzEE be a competitor for the Spring Cloud framework? He is certainly not as popular and advanced in the solutions for microservices like Spring Cloud, but has basic modules for service registration, discovery, distributed configuration propagation, circuit breaking, metrics and support for Docker and Kubernetes. It uses CDI on JBoss Weld container for dependency injection and Jersey as a REST API provider. Modules for configuration and discovery basing on Consul or etcd and they are rather on early stage of development (1.0.0-SNAPSHOT), but let’s try it out.
	----
	** RAHHHH, Istio Istio Istio qui semble être une solution de plus en plus préco pour MP : https://www.eclipse.org/community/eclipse_newsletter/2018/september/MicroProfile_istio.php (en plus un article récent !) -> *A LIRE ABSOLUMENT !!!!*
	** l'eBook "Building Microservices with Enterprise Java: A Practical Guide to Eclipse MicroProfile" http://bit.ly/MP-ebook, 62 pages 2018/10, A REGARDER
	** Voir aussi la vidéo de Susanne KAISER (toujours la même) en 14:40 : service mesh 

* *Comparaison entre Spring Boot / Cloud et MicroProfile* :

	** Spring vs JEE : l1 p6

	** https://www.ibm.com/blogs/bluemix/2018/09/migrate-java-microservices-from-spring-to-microprofile-p1/ : Très bonne ressource
		**** code source avec Spring : https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/spring
		**** code source avec MicroProfile : https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile

	** Pour *la partie vraiment "core"* du dev des microservices : https://developers.redhat.com/blog/2018/11/21/eclipse-microprofile-for-spring-boot-developers/ +
	-> Article très récent, 21/11/2018 +
	-> *Attention*, cela ne couvre PAS l'environnement technique adjacent (API gateway, service discovery, etc.)

	** Pour une comparaison du Health check, voir https://medium.com/ibm-cloud/java-microservices-with-microprofile-health-check-and-metrics-cd70cf529626 +
	Health Check avec Spring Actuator (inclus dans Spring Boot), voir l1 p63, réalisé par le Service Discovery

	** Pour une comparaison de 2 jours de workshops (plan de formation Oxiane) pour bâtir une application microservices, l'un avec MicroProfile, l'autre avec Spring, voir : https://www.oxiane.com/voxxeddays-microservices/ +
	TRES SYMPA POUR AVOIR *UN LISTING DE TECHNO CLASSÉ PAR CATÉGORIE* :
		**** (WS2) Microservices en Java (Spring) : https://www.oxiane.com/wp-content/uploads/2018/06/Voxxed-Microservices-2018-Programme-Formation-WS2-Spring-Cloud.pdf

			----
			Architecture microservices

			Gateway (Zuul, Traefik)
			Registry et service discovery (Eureka, Consul et Istio)
			Monitoring (stack Elastic, Prometheus)
			Cache distribué (Hazelcast, Ehcache, Infinispan, Memcached)
			Sécurité avec Spring Security (et un détail des modifications/améliorations proposées par JHipster)

			Développement de plusieurs microservices

			Spring Boot et Spring Cloud pour démarrer rapidement une gateway et des microservices
			Netflix Eureka ou Consul pour gérer l’annuaire de services
			Spring Cloud Config pour configurer l’ensemble de l’architecture
			Sécurité JWT ou OAuth2 (avec Keycloak)
			API gateway avec Zuul
			Monitoring avec la stack Elastic
			Docker pour tester facilement l’ensemble de l’architecture localement, et pour passer en production
			----

		**** (WS1) Microservices en Java (Java EE) : https://www.oxiane.com/wp-content/uploads/2018/06/Voxxed-Microservices-2018-Programme-Formation-WS1-Jakarta-EE.pdf 

			----
			Architecture microservices

			Registry et service discovery (Config, OPen API, Consul)
			Scalabilité (Fault Tolerance)
			Monitoring (Open Tracing + Metrics + Health Check)
			Sécurité (JWT + JWT Propagation)

			Développement de plusieurs microservices

			Services REST (JAX-RS + CDI)
			Parsing JSON (JSON-P + JSON-B)
			Consul pour gérer l’annuaire de services
			Config pour configurer l’ensemble de l’architecture
			Sécurité JWT et propagation des tokens JWT
			Monitoring
			Docker pour tester facilement l’ensemble de l’architecture localement, et pour passer en production
			----

	** *A lire absolument* (mars 2019, viens de sortir) : https://dzone.com/articles/programming-styles-spring-boot-vis-a-vis-with-ecli et sa suite https://dzone.com/articles/programming-styles-compared-spring-framework-vis-a


* Microservices reference architecture (IBM) : https://www.ibm.com/cloud/garage/architectures/microservices/reference-architecture
	** Jeter également un oeil au "Get started with a microservices architecture" qui est dispo avec
* Cast Codeurs 204, sur Netflix qui abandonne le développement de sa stack OSS au profit du fork que Spring a réalisé dessus ("eureka" remplacé par "spring-eureka", à revérifier)
* Cast Codeurs 206 et 207, vérifier, mais apparemment l'implémentation Thorntail de MicroProfile (en v4 actuellement) vis des moments difficiles (à 01:22:00)
* 12@13 d'Antonio GONCALVES sur l'architecture microservices
* RefCardz Spring Boot et microservices

* repo de Darren : https://gitlab.com/darren.boutros/devoxx-2019/tree/find_Mission/Spring-Cloud/mission/src/main

=== Reminders

.https://thenewstack.io/from-monolith-to-microservices/
----
Alistair Cockburn introduced the “ports and adapters” pattern, also called hexagonal architecture, in the context of building applications that can be tested in isolation. However, it has been increasingly used for building reusable microservices-based systems, as advocated by James Gardner and Vlad Mettler. A hexagonal architecture is an implementation of a pattern called  bounded context, wherein the capabilities related to a specific business domain are insulated from any outside changes or effects.
----

.What are microservices? - https://hub.packtpub.com/capability-model-microservices/
----
Microservices originated from the idea of Hexagonal Architecture coined by Alister Cockburn. Hexagonal Architecture is also known as thePorts and Adapters pattern.
----

.Microservices definition from Alistair Cockburn
----
Microservices originated from the idea of Hexagonal Architecture coined by Alister Cockburn. Hexagonal Architecture is also known as the Ports and Adapters pattern.

Microservices is an architectural style or an approach to building IT systems as aset of business capabilities that are autonomous, self-contained, and loosely coupled.
----

For this last ref, check:

* https://hub.packtpub.com/microservices-and-service-oriented-architecture/ : TRES BON pour décrire l'origine des microservices
* https://hub.packtpub.com/capability-model-microservices/

Good characteristics for microservices: https://stackoverflow.com/questions/48653762/how-microservices-are-different-from-isolated-standalone-service

Especially do not forget the argument on *independent life cycles* to use Conway's law to your advantage.

* https://blog.bernd-ruecker.com/3-common-pitfalls-in-microservice-integration-and-how-to-avoid-them-3f27a442cd07: excellent ref

----
Microservices are about decomposition, but giving each component a high degree of autonomy and isolation
----

This link also explains the importance of *failing fast*

* Parlez de CQRS / ES, et donc prévoir quelques mots sur *Axon framework*. 

* Il faudra peut-être (en fait, *SUREMENT*) également commencer par dire 2 mots sur la comparaison entre plateforme, comme *Istio*, et frameworks, comme *Spring* et *MicroProfile*, pour l'env tech des microservices. +
A ce sujet, voir la prez à Devoxx UK 2018 de Kate Stanley & Adam Pilkington (IBM) : https://www.youtube.com/watch?v=lFj8X0VLOFQ

Pour rappel : "Istio is an Open *platform* to connect, manage and secure microservices" +
Il prend en charge les fonctionnalités suivantes :

* Service Mesh
* Intelligent Routing and Load Balancing
* Fault Tolerance
* Policy Enforcement
* Metrics, Logging, Observability, Visualisation
* Service Identity and Security

Concernant Istio, le side car *Envoy* réalise les fonctionnalités suivantes :

* High performance C++ Proxy
* Load balancing
* Circuit breaking
* Health checks
* Fault injection

==== Kubernetes as a replacement for service registry, discovery and load balancing instead of Netflix OSS

Cette tendance se confirme de plus en plus, bien aidée par l'avènement de l'industrialisation des containers.

check https://www.ibm.com/blogs/bluemix/2017/05/key-decisions-when-building-microservices-apps-in-java-with-kubernetes/ :

----
Q3: How do I handle application service registry and discovery?

To benefit from the many Microservices you create in a distributed, elastic cloud environment, a proper service registration and discovery strategy is critical to allow them to communicate with each other or to be consumed. As a pioneer in cloud-native Microservices implementation, Netflix has built and released a set of opinionated libraries known as Netflix OSS, such as Eureka, Zuul, Ribbon, etc. And they are well integrated with the Spring framework. Typically, services are registered to Eureka, and Ribbon/Zuul handle the service discovery and basic load-balancing. However, what I describe was nearly 5 years ago.

Today, Kubernetes natively supports service registry, discovery and load balancing. You no longer need Netflix OSS for these tasks. Instead, you design the system the Kubernetes way. You can leverage Kubernetes’ Service type to expose your Microservices, then it automatically registered into Kubernetes system via virtual IP or DNS approach (I’ll elaborate on this decision in the next question/answer). The discovery will be through the familiar DNS lookup style. For Service-based clusters, Kubernetes provides a built-in load balancer to distribute the workload among Pods (containers).
----

Voir également https://www.ibm.com/blogs/bluemix/2018/09/migrate-java-microservices-from-spring-to-microprofile-p1/ :

----
However, the move to Kubernetes mostly obfuscated the need for Spring Cloud capabilities, as most of our microservice capabilities were supported out of the box by Kubernetes (with some minor exceptions like Hystrix fault tolerance support).
----

== Teaser et abstract

*Titre* :

* Microservices war! Spring vs Microprofile!
* Microservices battlefield! Spring vs Microprofile!
* *Microservices: Infinity War! Spring vs MicroProfile*

*Thèmes* : Cloud, Containers et Infrastructure, DevOps

*Niveau* : ouvert à tout niveau d'audience, débutant comme expert

*Type de présentation* : Slides et du code

*Abstract* :

idées à développer dans l'abstract : 

* environnement technique complexe
* donc on utilise des frameworks pour se simplifier la vie
* Spring, Boot et Cloud, est omniprésent, mais MicroProfile est maintenant un challenger
* peut-il espérer concurrencer Spring ?

----
En ce début 2019, et avec maintenant quelques années de recul (et quelques crises de nerf ?) sur le sujet, tout le monde s'accorde à dire que l'environnement technique nécessaire à la mise en place de **microservices** est complexe :
API gateway, service discovery et registry, design for failures et circuit breaker, gestion de la sécurité via OAuth et OpenID Connect, et j'en passe...

Le framework **Spring**, plus particulièrement les projets **Boot** et **Cloud**, a permis à bien des développeurs de préserver (une partie de ? 😉 ) leurs cheveux en facilitant cette mise en place.
Mais est-il seul roi en son domaine, ou existe-t-il des alternatives ?
Créé fin 2016 sur base de Java EE 7, le projet **Eclipse MicroProfile** a justement pour objectif d'optimiser la plateforme Java EE pour les architectures microservices.
Pourra-t-il concurrencer l'hégémonie du premier ?

Durant cette université, **nous comparerons les forces et faiblesses** de ces 2 plateformes via le **développement simultané, pour chacune d'elles, d'une même application**.  
Vous pourrez ainsi, en toute connaissance de cause, choisir de rester sur votre Spring, ou au contraire basculer sur le nouveau MicroProfile 😉
----

Message pour le comité :

----
Bonjour,

Le but de cette université est de **comparer les possibilités des frameworks Spring et MicroProfile pour le développement de microservices**, et leurs facilités d'intégration avec les outils du marché (Netflix OSS, stack Hashicorp avec Consul & Co, mais aussi l'omniprésent Istio du moment, etc.) assurant la qualité de service requise par les applications cloud-native (service discovery, load balancing, gestion des erreur, configuration centralisée, etc.).

On ne va pas se mentir, actuellement, pour le déploiement de microservices, Spring est de loin la stack la plus connue et utilisée.  
Or justement, nous voudrions justement montrer qu'elle n'est pas la seule, et que l'on peut **faire de belles choses avec notre "bon vieux" Java Enterprise**, ici avec MicroProfile 😉

Au final, nous voulons qu'en sortant de l'université, les participants sachent qu'elles sont les forces et faiblesses de chaque stack, et s'ils doivent en choisir eux-mêmes une à l'avenir, ne se contente plus d'un "Spring par défaut".

Côté speakers, Darren et moi faisons partie du **JUG Interne de Softeam depuis des années**.  
Pour une petite idée de notre activité, voir [les CR de nos réunions mensuelles sur GitHub](https://github.com/softeamfr/startech-meetings-reports).  
Nous sommes tous deux des devs seniors avec plus de 12 et 15 ans d'expérience, et plusieurs années d'architecture derrière nous.  
Via notre activité au JUG (voir [cette présentation](https://ardemius.github.io/slides-startech/slides-starTECH.html) pour plus de détails sur celle-ci) nous avons déjà donné de nombreuses formations aux développeurs de la société, sur des sujets variés (*Java core*, *Lambdas*, *optimisation*, *Spring*, *Git*, *TDD*, *AsciiDoctor*, etc.), nous avons donc l'habitude de prendre la parole en public.

Darren a été **enseignante en université pendant 6 ans** sur UML, ainsi qu'en développement web en Java / Java EE.  
De mon côté, **j'ai déjà été speaker à Devoxx France en 2017**, avec le sujet ["Sorcellerie en Java : outrepasser les interdits avec sun.misc.Unsafe"](https://cfp.devoxx.fr/2017/talk/FEU-0240/Sorcellerie_en_Java_:_outrepasser_les_interdits_avec_sun.misc.Unsafe.html) ([YouTube](https://youtu.be/FytJ4OdGYPM)), avec lequel j'avais également gagné le Young Blood du Paris JUG la même année ([YouTube](https://youtu.be/mPvhzKLb9K0))  
Je fais également parti du pôle formation de Softeam, tout particulièrement concernant Git.  
Une bonne partie de mon activité et ma veille est visible sur mes repo GitHub : [https://github.com/Ardemius](https://github.com/Ardemius)
----

Mots clés : microservices, Spring, MicroProfile, (Java EE)

== Présentation

Abréviations :

* l1 : Spring Microservices in Action
* l2 : MicroProfile

=== Intro

Les microservice c'est quoi ? A quoi servent-ils et à quels besoins nos 2 stacks doivent-elles répondre ?

Définition d'Alistair COCKBURN + reminder l1 p2 et p13 :

----
Microservices is an architectural style or an approach to building IT systems as aset of business capabilities that are autonomous, self-contained, and loosely coupled.

A microservice is a small, loosely coupled, distributed service

For microservices, keep in mind : Small, Simple and Decoupled Services = Scalable, Resilient and Flexible Applications
----

Pour l'émergence des microservices, voir l'excellent https://hub.packtpub.com/capability-model-microservices/ "What are microservices"

----
Microservices are not invented. 
Many organizations, such as Netflix, Amazon, and eBay, successfully used the divide-and-conquer technique TO FUNCTIONALLY PARTITION THEIR MONOLITHIC APPLICATIONS INTO SMALLER ATOMIC UNITS, and each performs a single function. These organizations solved a number of prevailing issues they experienced with their monolithic application. 
Following the success of these organizations, many other organizations started adopting this as a common pattern to refactor their monolithic applications. 
Later, evangelists termed this pattern microservices architecture.
----

-> l1 p13 : 

----
We’re at an inflection point in history. Almost all aspects of modern society are now wired together via the internet. 
Companies that used to serve local markets are suddenly finding that they can reach out to a global customer base. However, with a larger global customer base also comes global competition. 
----

Et pour une définition, l1 p2 : *a microservice is a small, loosely coupled, distributed service*

Microservices are *distributed systems*

Characteristics of microservices : (Voxxed microservices 2018 - Distant Path of Microservices)

* retries (importance de ce point confirmé dans "For a Future Microservices Journey")
* transaction manager
* Command objects
* service registry
* caching

Pour les caractéristiques, on a aussi :

.https://thenewstack.io/from-monolith-to-microservices/
----
One approach to building out this developer infrastructure is to create a standard boilerplate project that encapsulates *key principles of microservice design*, including project structure, test automation, integration with instrumentation and monitoring infrastructures, patterns like circuit breakers and timeouts, API frameworks, and documentation hooks, among others.
----

Insister sur *l'environnement autour des microservices*, et reprendre l'excellent schéma de Susanne Kaiser lors du Voxxed Microservices Preparing "For a Future Microservices Journey" +
On peut parler pour cet environnement de "capability model" (voir https://hub.packtpub.com/capability-model-microservices/ et https://www.oreilly.com/library/view/microservices-building-scalable/9781787285835/ch12s03.html)

notion d'isolation pour les microservices (trouver une ref plus précise), or *l'isolation amène la redondance* (DRY PLUS coupling OR isolation PLUS redundancy -> les microservices préfèrent le 2nd, cf conf VM "Hexagonal at Scale, with DDD and microservices!")

=== L'environnement autour des microservices (API Gateway, service discovery, fail-fast, etc.)

l1 p17 : "Microservices are more than writing the code"

-> Reprendre l'excellent schéma de Susanne Kaiser lors du Voxxed Microservices Preparing "For a Future Microservices Journey" +
https://www.youtube.com/watch?v=sIlQ5iYeqIE à partir de 02:15, et voir également la liste des techno nécessaires en 04:26

* Beaucoup de complexité découlant de l'infrastructure -> faire schéma !

* Hystrix et, de plus en plus, ses remplaçants : l'abandon d'#Hystrix au profit de #Resilience4j et #AdaptiveConcurrencyLimits (cf Fabrice Volkaert @volkaert)

* Voir également l1 p18 pour une description de ce que l'environnement des microservices doit garantir.
* ET SURTOUT VOIR L'EXCELLENTE l1 p27 avec le schéma associé !!!! (à reprendre ?)

NOTE: concernant l'API gateway (ou service gateway), bien voir la note l1 p156 sur leur conception, afin d'éviter qu'ils ne deviennent des bottlenecks

* Load Balancer : as soon as multiple instances are running	

* API Gateway : le point d'entrée unique pour tous les services, permet également d'implémenter plusieurs fonctionnalités transverses, dont les static et dynamic routing

* Asynchronous messaging : pour tout ce qui est communication Event Driven (RabbitMQ, Kafka). Permet d’améliorer le découplage des microservices. +
Attention toutefois, on peut devenir dépendant (donc re-couplage) de la version du type de message. Ex: JSON ne supporte pas nativement le versioning, contrairement à Avro (poussé par Kafka) 

* Immutable infrastructure l1 p25 (et §10) : "once a service is deployed, the infrastructure it's running on is never touched again by human hands"
* Infrastructure as code l1 p25 (et §10) +
-> les 2 sont obtenus via Docker

Parler également des serveurs renaissants ? (*phoenix servers*, cf Martin Fowler https://martinfowler.com/bliki/PhoenixServer.html) +
Par opposition aux servers "longue durée" (snowflake servers), voir https://www.thoughtworks.com/insights/blog/moving-to-phoenix-server-pattern-introduction

=== Focus sur le "core" des microservices

l1 p19 - 20 : les principales caractéristiques

Bien parler de la *communication entre microservices* : 

* synchrone : tight coupling, REST calls
* *asynchrone* : Rabbit / Kafka, loose coupling +
C'est bien ce type de comm qui est préconisé la plupart du temps pour les microservices

-> pour ce point, voir :

* https://dzone.com/articles/microservices-in-practice-1
* https://dzone.com/articles/introduction-to-microservices-messaging-protocols : donne les use cases des communications synchrones et asynchrones

	** *synchronous* : Use HTTP/REST (synchronous) communication for services outside of the internal microservices structure. +
	The HTTP/REST communication is ideal for external requests, as it’s built to easily handle items like real-time interactions from a client.
	** *asynchronous* : Use AMQP (asynchronous) for communication methods within the internal microservices structure +
	Asynchronous messaging protocols such as AMQP, STOMP or MQTT -> client doesn’t expects a response immediately, or not accepts a response at all +
	Asynchronous communication means that a service doesn’t need to wait on another to conclude its current task.

* https://dzone.com/articles/how-are-your-microservices-talking, qui repropose également une def des microservices :

----
Microservices can be thought of as minimal units of functionality, can be deployed independently, are reusable, and communicate with each other via various network protocols like HTTP (more on that in a moment).
----

=== Présentation de Sprint Boot et Cloud

Cf l1 p28 et p34 : définition de Spring Boot et Cloud

* Création de Spring Boot en avril 2014 (Spring Boot 1.0.0.release - https://mvnrepository.com/artifact/org.springframework.boot/spring-boot/1.0.0.RELEASE)
	** Actuellement (2019/04) en 2.1.4
* Création de Spring Cloud en mars 2015 (Spring Cloud 1.0.0, pre-Angel version)
	** Pour le release train, voir 
	Spring Cloud Greenwich -> Spring Boot 2.1.x
	Spring Cloud Finchley  -> Spring Boot 2.0.x

Refcardz DZone : Spring boot pas d'app server comparé à JEE classique : "Specifically, Spring Boot is concerned with building "bootable" applications that can boot up on bare metal or virtualized infrastructure without any elaborate ecosystem such as application servers or web containers".

=== Présentation de Microprofile

* Création de Eclipse MicroProfile en septembre 2016 (MicroProfile 1.0, voir l2 p43)
la 2.2 date elle de 2019/02

* Pour une très bonne définition de ce qu'est Eclipse Microprofile, voir l2 p37, et p43
* Voir également https://www.baeldung.com/eclipse-microprofile
* ET L'EXCELLENTE DEFINITION de tomitribe (fait partie des fondateurs de MicroProfile) : https://www.tomitribe.com/blog/what-is-eclipse-microprofile/
	** donne cette def de MicroProfile (vient de la MicroProfile FAQ)

----
The primary purpose of MicroProfile is to create a Java Enterprise framework for implementing portable microservices across vendor solutions.
----

Parler de Thorntail (anciennement Wildfly Swarm), Open Liberty, Payara, TomEE et mentionner qu'il existe d'autres implémentations de MicroProfile.
-> Voir https://developers.redhat.com/blog/2018/11/21/eclipse-microprofile-for-spring-boot-developers/

-> BREAKING NEWS ! 11/04 - blog de Ken Finnigan : https://thorntail.io/posts/thorntail-community-announcement-on-quarkus/ +
	Pour rappel, Ken Finnigan est le co-fondateur et leader du projet Wildfly Swarm / Thorntail

Parler de *"Just enough Application Server"*
Historiquement, un application server c'était *"one size fits all"* (l2 p41)
l2 p38 : 
"In a nutshell, JeAS *inverts* the relationship between an application server and an application, ensuring that *you package only the parts of an application server that your application requires*"
-> On peut en final créer un Uber jar avec MicroProfile "complet" (je rappelle que toutes ses spécifications sont dédiées au Microservices), OU seulement avec certaines de ses briques ("fractions" comme les nomme Thorntail), comme MicroProfile OpenTracing

NOTE: pour les *Hollow jar* (ou Hollow Uber jar), voir https://dzone.com/articles/an-introduction-to-hollow-jars :

----
A Hollow JAR is a single executable JAR file that, like an UberJAR, contains the code required to launch a single application. Unlike an UberJAR though, a Hollow JAR does not contain the application code.

A typical Hollow JAR deployment then will consist of two files: the Hollow JAR itself and the WAR file that holds the application code. The Hollow JAR is then executed referencing the WAR file, and from that point on the two files run much as an UberJAR would.
----

Payara micro a l'air de faire ça (https://blog.payara.fish/introducing-payara-micro) : java -jar payara-micro.jar --deploy test.war

Les avantages de JeAS sont décrits en l2 p41 :

* Réduction de la taille de l'application : comparée à la somme d'une application classique PLUS le serveur d'application
* Réduction de la mémoire allouée : va dépendre du nombre de classes qui n'auront plus besoin d'être chargées
* Réduction de la surface d'attaque : moins de ports d'ouverts, moins de services qui tournent
* Meilleure séparation entre les applications : comparé à un serveur d'app dans lequel on avait généralement plusieurs applications de déployées
* Mises à jour simplifiées : la mise à jour ne concerne plus QU'UNE application

-> Mais pourquoi on n'a pas fait ça avant ?! *le coût du matériel autrefois* (la machine) +
De nos jours, avec l’avènement des VM et des containers, le constat n'est plus le même

A la base, JEE 8 = 40 JSRs (voir https://www.oracle.com/technetwork/java/javaee/tech/index.html et https://blogs.oracle.com/java/java-ee-8-overview)

Voir également l'excellent talk d'Antonio GONCALVES (https://antoniogoncalves.org/2016/07/13/just-enough-app-server-with-wildfly-swarm/ le quickie à Devoxx UK 2016), pour une très bonne explication de ce qu'est Thorntail avec un exemple de code (comparé à un server d'app JEE classique) -> *le JeAS est compris dans un uber-jar, avec JUSTE les dépendances requises*

l2 p43 : Eclipse Microprofile : une initiative communautaire pour "optimiser Java Enterprise pour les microservices"
	** donne la liste de participants initiaux : *Red Hat, IBM, Tomitribe, Payara, the London Java Community*
*TRES BONNE DEF* - l2 p44 : Eclipse MicroProfile creates specifications for Enterprise Java microservices, with the benefit that microservices become portable between JeAS runtimes that support Eclipse MicroProfile.

2019/02/10 MicroProfile 2.2 : https://microprofile.io/2019/02/12/eclipse-microprofile-2-2-is-now-available/

Parler de Smallrye !!!! -> l'implémentation de MicroProfile de RedHat (cf Ken Finnigan dans sa note)

Le maître mot de Thorntail (https://thorntail.io/) : "Thorntail: Rightsize your Java EE Applications" +
Pour Thorntail, voir l2 p56 : Thorntail - the most flexible JeAS runtime

* Rebranding of WildFly Swarm 2018.5.0 to Thorntail 2.0.0 in late June 2018

Présenter les *différentes implémentations de MicroProfile* avec https://wiki.eclipse.org/MicroProfile/Implementation : +
SmallRye / Thorntail / Open Liberty / Payara Server et Micro +
-> permet également de récupérer le détail de chacune des implémentations de MicroProfile

[NOTE]
----
JAX-RS is just an API : Glassfish comes with the implementation *Jersey*, while Wildfly or Jboss come with *RESTEasy*.
*Weld* is the reference implementation of the abstract JSR-299 API, which is better known as *CDI*
----

DONC, le plan de cette partie :

1) just enough application server
	** Un exemple avec un microservice ne demandant que JAX-RS, CDI et JSON-P -> SCHEMA 1
	Pour l'exemple, voir https://www.baeldung.com/eclipse-microprofile
	** réutiliser le schéma l2 p42 en faisant apparaître la notion d'Uber jar ? -> SCHEMA 2
	** Pourquoi on a pas utiliser ce principe avant : *le coût du matériel autrefois* (l2 p43) +
	De nos jours, avec l’avènement des VM et des containers, le constat n'est plus le même
2) Eclipse MicroProfile pour JUSTE les features dont les microservices ont besoin ! +
	** Voir https://www.eclipsecon.org/france2018/sites/default/files/slides/MicroProfile-Meets-Istio.pptx +
	-> slide 2 pour une présentation des principale features de MicroProfile
	** Voir également https://fr.slideshare.net/radcortez/lightweight-enterprise-java-with-microprofile +
	-> slides 23 à 25
	** Et voir aussi la doc officielle : https://github.com/eclipse/microprofile/releases/tag/2.2 +
	-> le PDF dispo explique ce que fait chaque feature (*le mieux au final*)
3) Présentation des différentes implémentations

Implémentations supportant MicroProfile 2.2 :

SmallRye
Thorntail 2.4.0.Final
Open Liberty 19.0.0.3
WebSphere Liberty 19.0.0.3

=== Live Demo

* On commence par une rapide présentation de ce que va faire la démo

Bonne ressources à exploiter : https://developers.redhat.com/blog/2018/11/21/eclipse-microprofile-for-spring-boot-developers/

* IL VA FALLOIR UN PETIT DIAGRAMME DE CLASSE (diagramme d'archi) DE LA DEMO
* et lister les techno utilisées pour chaque stack

* Bien découper la démo, élément (classe) par élément dont on présentera l'implémentation successivement, en comparant systématiquement les stacks Spring et MicroProfile 
	** trouver un moyen simple d'afficher à l'écran, pour un même élément, les codes Spring et MicroProfile (via l'IDE ? 2 workspaces / projects en parallèle ?)
	** voir si on intègre un peu de code dans les slides

-> DANS TOUS LES CAS, venir le jour J avec plusieurs backups du code source COMPLET

=== Conclusion de la demo

* Etudier les possibilités de "mixer / mélanger" les 2 stacks
* Parler (rapidement) des possibilités d'implémenter ses microservices "à la main", sans framework tierce

On vous a parlé de création de microservices avec stack Spring et MicroProfile, mais d'autres solutions sont possibles, comme l'usage d'Istio (notion de *service mesh*). +
Rentrer dans le détail serait l'objet d'une présentation à part, mais on peut rapidement en dire ceci : bla bla bla (en faire une rapide présentation)

Pour un bon schéma de ce qu'est un service mesh, cf "For a Future Microservices Journey"

*PERFORMANCES*

Pour une comparaison des PERFORMANCES de SPring Boot / Thorntail / Server d'app avec un microservice simple, voir le tableau du slide 20 de ce doc : http://camelcasecon.de/pdf/06_thorntail/CamelCaseCon06_Thorntail.pdf

*Spring vs MicroProfile*

1) Spring Web vs JAX-RS : *pour exposer une API REST* +
-> https://developers.redhat.com/blog/2018/11/21/eclipse-microprofile-for-spring-boot-developers/

SPRING
@RestController
@RequestMapping

MP
1 classe Application *en plus comparé à Spring* : donne un préfixe global pour tous les endpoints JAX-RS

----
@ApplicationPath("/api")
	public class ApplicationConfig extends Application {
}
----
ET

----
@Path("/greeting") // 1
@Produces(MediaType.APPLICATION_JSON) // 2
public class GreetingResource {

   @GET // 3
   public Response greeting(@QueryParam("name") @DefaultValue("World") String name) {  // 4
      ...
   }
----

Pour les *query parameter* : @RequestParam en Spring MVC contre @QueryParam en MicroProfile

Parler de @Context pour injecter des valeurs telles que headers HTTP (ou security context) aux méthodes ou endpoints

2) *Injection de dépendances* : Spring framework vs CDI

SPRING
@Autowired

MP
@Inject

Comme Spring, CDI a le concept de beans qui vivent dans un scope donné :
@Scope pour Spring -> @ApplicationScoped, @RequestScoped, etc. pour CDI

Seule réelle différence, *le scope par défaut* :
*singleton* pour Spring, et *@Dependent* pour CDI +
-> correspond à *prototype* en Spring : "Scopes a single bean definition to any number of object instances."

NON, pas la configuration
3) *Configuration* : pour injecter les valeurs de configuration

SPRING : @Value et @PropertySource
Voir https://www.baeldung.com/spring-value-annotation

MP : @Inject et @ConfigProperty

----
@Inject
@ConfigProperty(name = "greeting.message")
private String message;
----

4) Documentation en général

Les tutoriaux sont bons dans les 2 cas
* https://openliberty.io/guides/

5) JPA

=== L'avenir

* gRPC poussé par l'omniprésence de Kubernetes, la caractéristique HTTP / REST / JSON des microservices va peut-être (sûrement ?) évoluer +
-> voir la vidéo "Intro to gRPC: A Modern Toolkit for Microservice Communication" (https://www.youtube.com/watch?v=RoXT_Rkg8LA)
	** voir également ce que pourrait donner GraphQL à la place de REST à ce sujet. Voir le blog d'Octo https://blog.octo.com/graphql-et-pourquoi-faire/, le plus important :
	"*L’optimisation des requêtes* ainsi que *l’optimisation des données réseaux* sont à mon sens les deux avantages majeurs de GraphQL à l’état de l’art."
* *Kubernetes / Istio* comme concurrent de Spring et Microprofile
* *Netflix arrête le support de sa stack OSS* pour supporter les outils Spring issus du fork de cette dernière (à checker, voir les Cast Codeurs 204)
* Absolument parler de Quarkus qui va remplacer Thorntail, voir la note de Ken Finnigan du 11/04/2019 : https://thorntail.io/posts/thorntail-community-announcement-on-quarkus/

== Dans l'absolu

* Plutôt vers le début, on pourrait parler un peu de la *décomposition du problème métier*, et donc du DDD 

* "Comme son titre l'annonce, cette présentation a pour but de comparer les stacks Spring, avec Boot et Cloud, et MicroProfile pour le développement d'une application basée sur une architecture microservices +
Donc, avant d'aller plus loin, commençons par rappelez ce qu'on entend exactement par architecture microservices."
* "Rapide sondage : qui a déjà utilisé ou utilise des microservices dans son projet ?"
	** Parmi celles et ceux qui ont répondu "oui", vos microservices reposent-ils principalement sur une stack Spring ?
	** une stack MicroProfile ?
	** ou aucune des 2, et vous faites tout à la main !!!! (réfléchir à la pertinence de la question)

== PLAN au 01/04/2019

0. présentation des speakers
1. rapide définition de ce qu'est un microservice et un peu d'histoire
	** un rien d'histoire : 
		**** *monolith (single unit) -> SOA (coarse-grained) -> microservices (fine-grained)* +
		Pour un bon schéma de cette évolution, partir de ce schéma : https://www.researchgate.net/figure/Evolution-from-monolithic-applications-to-microservices-based-systems_fig1_327758387, et préciser la partie SOA en faisant apparaître l'ESB comme indiqué ici : https://www.capgemini.com/2016/06/microservices-in-cloud-based-infrastructure-paving-the-way-to-the/ +
		Ce schéma propose une autre version de l'ESB : https://1904labs.com/work/case-studies/breaking-monoliths/ (*Smart endpoints and Dumb pipes* pour "dumb messaging system" pour les microservices, par opposition à la complexité métier de l'ESB, voir l'article original de *Martin Fowler* : https://martinfowler.com/articles/microservices.html#SmartEndpointsAndDumbPipes) +
		-> On abandonne l'ESB et sa complexité en passant aux microservices (microservices = "dumb" messaging environment : https://www.journaldunet.com/solutions/cloud-computing/1166432-microservices-est-ce-realiste/1167035-le-concept-des-microservices) +
		Faire également apparaître la *granularité* (single unit -> coarse-grained -> fine-grained : https://dzone.com/articles/microservices-vs-soa-whats-the-difference) et le *couplage* (tight coupling -> looser coupling -> decoupled : https://www.journaldunet.com/solutions/cloud-computing/1166432-microservices-est-ce-realiste/1167035-le-concept-des-microservices)
		**** *hexagonal architecture et définition d'Alistair Cockburn d'un microservice*
			****** rappeler les caractéristiques d'un microservice, voir l1 p13 entre autres
	** parler des principaux use cases adressés par les microservices
		**** migration from monolith : le use case d'origine (2010s, plutôt 2014 cf Google Trends pour l'apparition du terme microservices)
		**** cloud native app
2. le "core" des microservices
	** principaux concepts : REST et communication en JSON -> en gros, redonner une définition "technique" des microservices "seul dans leur coin" 
3. puis tout l'environnement qui gravite autour. On va y distinguer : +
-> pour chaque feature, max 1 à 2 lignes d'explication
	** API Gateway
	** Service Discovery
	** Load Balancer
	** Design for failure
		**** Circuit Breaker
		**** bulkheads : voir l1 p136
		**** fallbacks
	** Centralised configuration
	** monitoring and logging
	** security
-> bien faire une présentation *AGNOSTIQUE à la techno* à ce niveau. +
Faire un schéma global sur le modèle de celui de Susanne KAISER lors du Voxxed Days microservices 2018 (du début jusqu'à 05:25)

ON PLACE LES 15 20 min de pause ICI ! 

4. Les forces en présence pour le passage à la pratique ! +
-> on ne va PAS pouvoir TOUT tester, ni parler de tout (il n'y aura PAS de DDD, CQRS ou ES ici), mais on va essayer de montrer comment le "core" est réalisé pour chaque stack, quelle est un peu "sa philosophie", et COMMENT ELLE S'ADAPTE / PERMET LA MISE EN PLACE DU CAPABILITY MODEL
	** Présentation de la stack Spring pour les microservices (à avoir les projets Spring Boot et Cloud)
		**** Que fait Spring Boot ? Que fait Spring Cloud ?
	** Présentation de la stack Microprofile -> ON PART SUR *OPEN LIBERTY*
		**** présenter les principales implémentations de la spec MicroProfile (et donner la dernière version actuelle !)
		**** VEILLE TECHNO : warning sur Thorntail BIEN À VÉRIFIER (Cast Codeurs 207)
	** Présentation des grandes techno pour l'environnement et l'infrastructure
		**** l'historique : Netflix OSS
		**** La stack Hashicorp
		**** les nouveaux qui grandissent vite (cf l'autre présentation au même Devoxx par exemple)
	** Présentation exhaustive des technos AVEC LES VERSIONS que nous avons choisies pour les 2 stacks 
		**** Spring
		**** MicroProfile
			****** JAX-RS
			****** CDI
	** Darren : slide pour différencier les tests (unit / intégration / Pact (consumer-driven contract testing library) (chapitre 4 MicroProfile : Spring Cloud Verifier / équivalent pour MicroProfile))
		**** Dans notre cas, Spring est plus poussé côté test. Avec MicroProfile, il faut passer par Arquilian
	** Demo
		**** QUE VA FAIRE L'APPLICATION DE DEMO !!!! +
		-> ON VA CODER LE GANTELET DE L'INFINI ! +
		1 mission consiste en la récupération d'une gemme +
		Thanos part en mission, va rencontrer sur son chemin (lors de ses missions) nos héros (il va rencontrer Thor pour le service discovery, Tony Stark pour le load balancer, etc.)
		pour illustrer la prez : 1 super hero par feature de l'environnement microservices +
		**** Explication du Consumer Driven Contract (CDC) qu'on va utiliser. +
		Voir les ressources :
			****** https://thoughtworks.github.io/pacto/patterns/cdc/ : explication très globale du CDC
			****** http://dhaval-shah.com/microservices-and-consumer-driven-contract-testing-using-pact/ : de très bonne explications sur les avantages du CDC pour les microservices
			****** https://www.baeldung.com/pact-junit-consumer-driven-contracts : le très pragmatique site de Baeldung (très bon exemple), utilisant la techno *Pact*
			****** la doc officielle : https://docs.pact.io/how_pact_works
		**** Diagramme d'architecture
		**** Fonctionnalités de l'environnement des microservices que nous allons faire intervenir
			****** on ne va PAS parler de la modélisation du domaine (et donc du DDD) qui est indépendante de la stack technique
		**** step by step : slide (diag archi avec en couleur brique de l'étape) PUIS codage +
		ordre des étapes :
			****** REST
			****** Service
			****** DAO (et domain ?)
5. Conclusion : récapitulatif des points communs / différences entre les 2 stacks
	** Spring est très vite "up to date" avec l'état de l'art du marché +
	-> LA TOUCHE DE FIN : Gif animé (ou image fixe et texte incrusté) de Thanos en train de sourire après avoir trucidé la moitié de l'univers. +
	Avec cette question : Entre Spring et Microprofile qui Thanos supprime-t-il de l'univers ?
6. BONUS DE FIN ! Infinity War 2 -> Quelle pourrait être la suite ?
	** les protocoles de communications : gRPC poussé par Kubernetes, et GraphQL
	** "l'autre combattant" Kubernetes (avec le service mesh Istio)
	** Et maintenant Quarkus ! https://developers.redhat.com/blog/2019/03/07/quarkus-next-generation-kubernetes-native-java-framework/
7. On réserve 10 min pour les questions

-> Au total, ~2h30 de présentation (slides et demo)

NOTE: voir si on ne parle pas d'autres techno similaires en bonus de fin : "Projects like *Dropwizard*, Spring Boot, and *Netflix Karyon* are interesting approaches to solving this"

=== 1 rapide définition de ce qu'est un microservice et un peu d'histoire

max 2 à 3 slides

Confère le livre Spring in action (voir pages annotées) : microservices comme principal architecture pattern pour le développement d'application cloud +
-> la migration d'un monolithe vers une application microservices sont un 1er use case (historique), le 2nd et "main stream" maintenant sont les applications cloud-native. +
Sur ce point, voir l1 p6

Pour une def d'applications *cloud native* (en comparaison à cloud ready), voir https://www.entando.com/page/en/what_is_the_difference_between_cloudready_and_cloudnative?contentId=BLG4585 +
Autre très bonne ressource sur tout ce qui touche les applications cloud-native : le CNCF (*Cloud Native Computing Foundation*) *Cloud Native Interactive Landscape* (https://github.com/cncf/landscape et l'*EXCELLENT* https://landscape.cncf.io/) -> Donne un panorama de toutes les techno pouvant être utilisées pour réaliser des applications cloud native
Une autre très bonne def des applications cloud-native ici : https://medium.com/walmartlabs/cloud-native-application-architecture-a84ddf378f82 :

----
Cloud native is an approach for building applications as micro-services and running them on a containerised and dynamically orchestrated platforms that fully exploits the advantages of the cloud computing model.
Cloud-native is about HOW applications are created and deployed, NOT WHERE.
----

Voir également la vidéo de Pivotal (~2 min) sur ce qu'est *l'approche Cloud Native* : https://pivotal.io/fr/cloud-native +
Elle insiste sur ces 3 caractéristiques :

* *architecture microservices* : implies multiple, independent teams working to make a system better
* *Continuous Delivery* : CD is a clear, automated path that lets developers rapidly deploy to production environments
* *DevOps* : DevOps culture helps developers and operations work together to deliver shared value to the customer

TRES IMPORTANT : *Cloud-native is about how applications are created and deployed, not where* (def dans plusieurs ressources, dont ici : https://medium.com/walmartlabs/cloud-native-application-architecture-a84ddf378f82)

Se servir de cette image de Pivotal : https://cdn-images-1.medium.com/max/358/1*8tS36qcyZ2c-kYF3zSrbfA.png

== Programme de la journée du 04/04/2019

* slides de présentations des speakers (nous)
* faire fonctionner demo sur machine Thomas (test et backup AU CAS OU en cas de pépin pour la conf)
* test de défilement des slides sur un écran projeté
* se mettre d'accord "finement" sur le plan

=== Pour la prochaine fois 16/04/2019

* TESTER UNE TELECOMMANDE pour la présentation (ramener ma Logitech laser)

5 composants

* service discovery avec Consul : Spring et MicroProfile
* load balancer avec Fabio : Spring et MicroProfile
* design for failure avec Hystrix : Spring et MicroProfile
* log correlation avec Sleuth
* distributed tracing avec Zipkin



Contrat : (2 microservices au moins)

Mission createMission(Stone, Place)
	getStone(Stone.name)
List<Stone> findAllStones

Darren m'envoie les paramètres pour le contrat

Mission : stone + lieu + ...

DevTool

EXPLIQUER LE CONTRAT POUR LES 2 MICROSERVICE !

45 minutes de slides
30 min de codage : REST Controller et service
BREAK -> 15 à 20 minutes ("rendez-vous à 11h05")
suite de la demo
Conclusion : 15 min

Démarrage de Spring Boot
Démarrage de Spring Cloud
Démarrage de MicroProfile

Mardi : il faut qu'on se mette d'acord sur les quetsions à se poser durant la démo
Voir comment créer une discussion entre nous à partir du slide "passage à la pratique" et jusqu'à la demo

-> insister sur la présentation des starters, les comparer, et préciser qu'ils permettent de choisir des briques du capability model
	** *Est-ce que Open Liberty dispose d'un starter* ? Apparemment non (j'ai pas trouvé)
	-> comment vas-tu initier le projet pour la démo ?


== AMELIORATIONS AU DERNIER MOMENT

* slide du capability model : augmenter la taille de police

== INFO DIVERS

Comme Node.js, Vert.x est une implémentation du design pattern reactor. +
Reactor is a fourth-generation Reactive library for building non-blocking applications on the JVM based on the Reactive Streams Specification



