= Microservices : Infinity War ! Spring vs MicroProfile
Thomas SCHWENDER <https://github.com/ardemius[@ardemius]>
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: ./images
:source-highlighter: highlightjs
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
:toclevels: 2
// To turn off figure caption labels and numbers
//:figure-caption!:
// Same for examples
//:example-caption!:
// To turn off ALL captions
:caption:

//toc::[]

Talk présenté à *Devoxx France 2019* (Université, 3h), avec ma collègue https://github.com/darrenboutros[Darren Boutros]. +
Nous sommes tous deux membres du *JUG de Softeam* (le https://ardemius.github.io/slides-startech/slides-starTECH.html[StarTECH Java] 😃)

La *vidéo* est disponible https://www.youtube.com/watch?v=2VH8rQSKdk0&list=PLTbQvx84FrARfJQtnw7AXIw1bARCSjXEI[ici] (chaîne YouTube de Devoxx France), et les *slides* link:resources/Microservices%20_%20Spring%20vs%20MicroProfile.pptx[là] (répertoire "resources" du présent repo).

NOTE: J'ai également écrit un https://ardemius.github.io/microservices-spring-vs-microprofile/microservices-etat-des-lieux.html[*article*] reprenant le contenu de la présentation, accessible via les https://ardemius.github.io/microservices-spring-vs-microprofile/microservices-etat-des-lieux.html[GitHub pages du repo].

Abstract :

____
En ce début 2019, et avec maintenant quelques années de recul (et quelques crises de nerf ?) sur le sujet, tout le monde s'accorde à dire que l'environnement technique nécessaire à la mise en place de microservices est complexe : API gateway, service discovery et registry, design for failures et circuit breaker, gestion de la sécurité via OAuth et OpenID Connect, et j'en passe...

Le framework Spring, plus particulièrement les projets Boot et Cloud, a permis à bien des développeurs de préserver (une partie de ? 😉 ) leurs cheveux en facilitant cette mise en place. Mais est-il seul roi en son domaine, ou existe-t-il des alternatives ? Créé fin 2016 sur base de Java EE 7, le projet Eclipse MicroProfile a justement pour objectif d'optimiser la plateforme Java EE pour les architectures microservices. Pourra-t-il concurrencer l'hégémonie du premier ?

Durant cette université, nous comparerons les forces et faiblesses de ces 2 plateformes via le développement simultané, pour chacune d'elles, d'une même application.
Vous pourrez ainsi, en toute connaissance de cause, choisir de rester sur votre Spring, ou au contraire basculer sur le nouveau MicroProfile 😉
____

